### ISSUE TITLE
AssertionError.Error should be an error subclass

### ISSUE THREAD

**Issue by fivetanley** [emberjs/ember-dev#149]
https://github.com/emberjs/ember-dev/blob/4155a367694b0cdc6c926429f689b33d3e785cd5/addon/test-helper/assertion.js#L10

Otherwise we get no stack :(

**Comment by rwjblue** [comment]
https://github.com/workmanw/ember-qunit-assert-helpers was extracted from the concepts in this repo, and does throw valid errors.  We should work to get ember-data and ember updated to use that addon ASAP...
