### ISSUE TITLE
How can I use expectDeprecation in addon tests?

### ISSUE THREAD

**Issue by taras** [emberjs/ember-dev#158]
I'm working on an addon that will be introducing some deprecations. I would like to test that a deprecation warning was raised. @mixonic suggested to use `expectDeprecation` but I haven't been able to get this library injected into my addon's test environment.

I tried installing this library as an addon and added the following to my `test-helper.js`

``` js
import Ember from 'ember';
import setupQUnit from 'ember-dev/test-helper/setup-qunit';
import EmberDevTestHelperAssert from 'ember-dev/test-helper/index';

var testHelpers = new EmberDevTestHelperAssert(Ember, false);
setupQUnit(testHelpers);
```

I expect to get expectDeprecation in my tests, but it doesn't look like it's available. 

How do I get this working?

**Comment by taras** [comment]
After looking at tests, I got it working like this

```
import {
  module,
  test
} from 'qunit';
import parseArgs from 'ember-ajax/utils/parse-args';
import createExpectDeprecationAssertion from '../../helpers/expect-deprecation';

let assertion;
module('utils/parse-args', {
  beforeEach() {
    assertion = createExpectDeprecationAssertion();
    assertion.inject();
  },
  afterEach() {
    if (assertion) {
      assertion.restore();
      assertion = null;
    }
  }
});

test('raises deprecation', function(assert){
  expectDeprecation(function(){
    let args = parseArgs.call(null, { url: '/posts'} );
  });
});
```

Should we make this easier?

**Comment by taras** [comment]
It looks like my example above didn't actually catch any deprecation warnings even though they're written to the console.

**Comment by rwjblue** [comment]
https://github.com/workmanw/ember-qunit-assert-helpers was extracted from the concepts in this repo...
