### ISSUE TITLE
Make helpers usable in apps/addons

### ISSUE THREAD

**Issue by slindberg** [emberjs/ember-dev#163]
Related: #158

These assertions are valuable for addon development to facilitate changing APIs, but are also useful for coordinating changes in apps with large teams. Ideally, these helpers would be included in a build tree as part of a cli addon, making them directly importable in tests, e.g.

``` js
// tests/integration/post-list.js
import hbs from 'htmlbars-inline-precompile';
import { describeComponent, it } from 'ember-mocha';
import { expectDeprecation } from 'ember-dev-mocha';

describeComponent('post-list', 'PostListComponent', { integration: true }, function() {
  it("should trigger a deprecation when specifying the `sortBy` attr", function() {
    expectDeprecation(() => {
      this.render(hbs`
        {{#post-list sortBy="nope"}}
      `);
    }, /The `sortBy` attribute is deprecated, pass in a sorted list instead./);
  });
});
```

Questions:
- Should this project be the target addon for all test frameworks, or should it act like [`ember-test-helpers`](https://github.com/switchfly/ember-test-helpers) and be designed for framework-specific addons to consume?
- If the later, what should the external assertion API look like? Is a single boolean assertion adequate, or should it support multiple assertion types?
- Should this project be de-addon-ified (supplying a `/lib` dir like ember-test-helpers)
- Should separate addons be created (e.g. `ember-dev-qunit`/`ember-dev-mocha`), or should support be added directly to `ember-mocha` and `ember-qunit`?
- If the later, is it safe to use chai style `expect(...).to.be` assertions?

cc @mixonic @mmun @rwjblue @dgeb

**Comment by mmun** [comment]
- Don't inject anything onto globals (as in your examples, just wanted to add this explicit requirement).
- We don't have to solve the mocha story, but we should factor things as best we can.

**Comment by rwjblue** [comment]
https://github.com/workmanw/ember-qunit-assert-helpers was extracted from the concepts in this repo...
