### ISSUE TITLE
Can ignoreDeprecation be updated to allow asynchronous execution

### ISSUE THREAD

**Issue by eshtadc** [emberjs/ember-dev#165]
Using ignoreDeprecation only applies to synchronous code.  In talking with @mixonic he suggested that one way to handle this is to allow the function parameter passed in to be optional.  If called without the function, deprecations would just be ignored to the end of the test run.

**Comment by rwjblue** [comment]
Ya, but I'd rather work on changes to https://github.com/workmanw/ember-qunit-assert-helpers and migrate consumers to that...
