### ISSUE TITLE
Modernizing this addon?

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember-dev#167]
This addon has some good stuff in it. Being able to know that your application hit no deprecations, warnings, or asserts during testing is actually pretty cool. But just poking around it doesn't seem like a lot of people are using this. Maybe because they don't know about it or maybe there is a simpler way to do that?

This library could use a little modernizing ... e.g. it doesn't support QUnit 2. I'd be happy to investigate this if others would find value in it. Then again, maybe ember-test-helpers and ember-qunit would be a better place for those asserts. Any thoughts?

**Comment by workmanw** [comment]
Hmm. So I've spent 3-4 hours looking into this. IMHO, the best solution is either 1) a rewrite of this addon or 2) simply a new addon that provides attribution to this one.

Much of this addon is about managing global QUnit test helpers injected to and removed from the window. I think the implementation here is solid, but also meant for another era. For that reason, I'm going to take option 2. I'll create a new addon that is a little more lean and see where it goes.

**Comment by rwjblue** [comment]
@workmanw - Please keep as a requirement that both Ember itself, and addons/apps can use it.  I'm happy to help collaborate...

**Comment by workmanw** [comment]
FWIW, I did end up making a new ember-addon with @rwjblue's help. https://github.com/workmanw/ember-qunit-assert-helpers

Obviously it is specific to QUnit 2.0. I'm going to be updating `ember-data-model-fragments` to QUnit 2.0 and replacing `ember-dev` with that addon to see how well it works. Perhaps when ember and ember-data make the same jump, they can also get value from that addon.

**Comment by sly7-7** [comment]
Thanks both of you @rwjblue and @workmanw. Today I started to update ember-cli for ember-data, I think your new addon will save me 👍
